import { jsPDF } from "jspdf";

interface GapItem {
  entity: string;
  entity_type: string;
  priority: string;
  recommendation: string;
}

interface ReportData {
  id: string;
  query: string;
  entities_found: number;
  user_entity_coverage: number;
  top3_entity_coverage: number;
  gaps: GapItem[];
  checklist: string[];
  timestamp?: string;
}

let fontReady = false;

/** Load Roboto font (Cyrillic-capable) into jsPDF */
async function ensureFont(doc: jsPDF): Promise<void> {
  if (fontReady) return;
  const resp = await fetch(
    "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/fonts/Roboto/Roboto-Regular.ttf"
  );
  const buffer = await resp.arrayBuffer();
  const base64 = btoa(
    new Uint8Array(buffer).reduce((d, b) => d + String.fromCharCode(b), "")
  );
  doc.addFileToVFS("Roboto-Regular.ttf", base64);
  doc.addFont("Roboto-Regular.ttf", "Roboto", "normal");
  fontReady = true;
}

/** Generates Markdown report and downloads */
export function downloadMarkdown(report: ReportData) {
  const lines: string[] = [];

  lines.push(`# SERP X-Ray: ${report.query}`);
  lines.push("");
  lines.push(`**ID:** \`${report.id}\``);
  if (report.timestamp) lines.push(`**Date:** ${report.timestamp}`);
  lines.push(`**Entities found:** ${report.entities_found}`);
  lines.push(`**Top-3 coverage:** ${report.top3_entity_coverage}%`);
  lines.push(`**Your page coverage:** ${report.user_entity_coverage}%`);
  lines.push(`**Gaps:** ${report.gaps?.length || 0}`);
  lines.push("");

  if (report.gaps?.length) {
    lines.push("## 🔴 Gaps");
    lines.push("");
    lines.push("| Priority | Entity | Type | Recommendation |");
    lines.push("|----------|--------|------|----------------|");
    for (const g of report.gaps.slice(0, 30)) {
      lines.push(
        `| ${g.priority} | ${g.entity} | ${g.entity_type} | ${g.recommendation} |`
      );
    }
    lines.push("");
  }

  if (report.checklist?.length) {
    lines.push("## ✅ Checklist");
    lines.push("");
    for (const item of report.checklist) {
      lines.push(`- ${item}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by SERP X-Ray*");

  const blob = new Blob([lines.join("\n")], { type: "text/markdown" });
  triggerDownload(blob, `serp-xray-${report.id}.md`);
}

/** Generates PDF report and downloads */
export async function downloadPDF(report: ReportData) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  await ensureFont(doc);
  doc.setFont("Roboto");

  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = margin;

  // Title
  doc.setFontSize(16);
  doc.text("SERP X-Ray", margin, y);
  y += 8;

  doc.setFontSize(12);
  doc.text(report.query, margin, y);
  y += 6;

  doc.setFontSize(8);
  doc.setTextColor(100);
  doc.text(
    `ID: ${report.id}  |  Entities: ${report.entities_found}  |  Gaps: ${report.gaps?.length || 0}`,
    margin, y
  );
  y += 10;

  // Gaps table
  if (report.gaps?.length) {
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text("Gaps", margin, y);
    y += 6;

    doc.setFontSize(7);
    const cols = [
      { title: "Priority", w: 18 },
      { title: "Entity", w: 30 },
      { title: "Type", w: 18 },
      { title: "Recommendation", w: pageWidth - margin * 2 - 66 },
    ];

    let x = margin;
    for (const col of cols) {
      doc.setFillColor(240, 240, 240);
      doc.rect(x, y - 4, col.w, 6, "F");
      doc.text(col.title, x + 1, y);
      x += col.w;
    }
    y += 4;

    for (const g of report.gaps.slice(0, 25)) {
      if (y > 270) { doc.addPage(); y = margin; }
      x = margin;
      doc.text(g.priority, x + 1, y); x += cols[0].w;
      doc.text(g.entity, x + 1, y); x += cols[1].w;
      doc.text(g.entity_type, x + 1, y); x += cols[2].w;
      const recLines = doc.splitTextToSize(g.recommendation, cols[3].w - 2);
      doc.text(recLines, x + 1, y);
      y += Math.max(5, recLines.length * 3.5);
    }
    y += 8;
  }

  // Checklist
  if (report.checklist?.length) {
    if (y > 260) { doc.addPage(); y = margin; }
    doc.setFontSize(11);
    doc.setTextColor(0);
    doc.text("Checklist", margin, y);
    y += 6;
    doc.setFontSize(8);
    for (const item of report.checklist) {
      if (y > 275) { doc.addPage(); y = margin; }
      const lines = doc.splitTextToSize(`• ${item}`, pageWidth - margin * 2);
      doc.text(lines, margin, y);
      y += lines.length * 4;
    }
  }

  doc.save(`serp-xray-${report.id}.pdf`);
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}